# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb:10.2
    namespace: koudom300003751175-intel
    uid: 302430d1-9ef5-499b-a8ce-a255905355e2
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: changeme
    restart: on-failure
    volumes:
     - ~:/var/lib/mysql

  adminer:
    image: adminer
    namespace: koudom300003751175-intel
    uid: 302430d1-9ef5-499b-a8ce-a255905355e2
    restart: always
    ports:
      - 8080:8080
